version: 2
defaults: &defaults
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check docker is running
          command: docker info
      - run:
          name: Pull Community Hass.io Add-ons build environment
          command: docker pull hassioaddons/build-env:latest
      - run:
          name: Log in to Docker Hub
          command: |
            if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
            then
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            fi
      - checkout
      - deploy:
          name: Build and (maybe) deploy
          command: |
              if [[ ! -z "${CIRCLE_TAG:-}" ]]; then
                docker run \
                  --privileged \
                  -v ~/.docker:/root/.docker \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --target example \
                  --${ARCH} \
                  --version ${CIRCLE_TAG#v} \
                  --tag-latest \
                  --push              
              elif [[ "${CIRCLE_BRANCH}" = "master" ]]; then
                docker run \
                  --privileged \
                  -v ~/.docker:/root/.docker \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --target example \
                  --${ARCH} \
                  --version ${CIRCLE_SHA1:0:5} \
                  --tag-test \
                  --push
              else
                docker run \
                  --privileged \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --target example \
                  --${ARCH}
              fi
      - deploy:
          name: Send notification to Microbadger
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                curl -X POST https://hooks.microbadger.com/images/${MICROBADGER_WEBHOOK}
              fi

jobs:
  aarch64:
    <<: *defaults
    environment:
      ARCH: aarch64
      MICROBADGER_WEBHOOK: hassioaddons/example-aarch64/-Dsmq0eEcKOq2p99bLUJj19dsxw=
  amd64:
    <<: *defaults
    environment:
      ARCH: amd64
      MICROBADGER_WEBHOOK: hassioaddons/example-amd64/6y5xU8A6MPYM7MpwC3jx6UUMiII=
  armhf:
    <<: *defaults
    environment:
      ARCH: armhf
      MICROBADGER_WEBHOOK: hassioaddons/example-armhf/H4v2thSWt5AJDl2_zNgujH0x_NA=
  i386:
    <<: *defaults
    environment:
      ARCH: i386
      MICROBADGER_WEBHOOK: hassioaddons/example-i386/MhziqAtkr5Xpo9irIKe0qbsF5T8=

workflows:
  version: 2
  build_and_maybe_deploy:
    jobs:
      - aarch64:
          filters:
            tags:
              only: /.*/
      - amd64:
          filters:
            tags:
              only: /.*/
      - armhf:
          filters:
            tags:
              only: /.*/
      - i386:
          filters:
            tags:
              only: /.*/
